### ISSUE TITLE
Alternative / gallery view

### ISSUE THREAD

**Issue by heijligers** [lanec/zoom-batch-downloader#1]
Currently the script  only seems to download the speaker view. I would like to download all 3-5 different views.

**Comment by ajippolito** [comment]
Hi Heijligers - did you ever figure this out?  I've got the script working and am encountering the same issue.

**Comment by heijligers** [comment]
Yes i did. I modified the script to include the other views too. Let me check tomorrow how to merge my changes back into this script.

**Comment by AnessZurba** [comment]
Should work with the new version, it downloads all the records for a specific meeting, even the chat log
