### ISSUE TITLE
Editing cloudlink.py

### ISSUE THREAD

**Issue by aviamo** [lanec/zoom-batch-downloader#10]
Hi, I am very new to Python & all.
You write:
"Edit cloudlink.py to include your JWT token, the correct path for your downloads, and the USER ID from Zoom's API."

Where should we add our Token, path and User ID in the cloudlink.py file?

**Comment by AnessZurba** [comment]
Note that the script has been updated to use server to server auth as JWT is deprecated

in the start of the file you have

```
# Zoom API credentials
ACCOUNT_ID = '##########'
CLIENT_ID = '##########'
CLIENT_SECRET = '##########'

# Put your USER ID that you get from the API. 
USERID = '##########'
```

replace the "#"s with your credentials

**Comment by AnessZurba** [comment]
closed due to inactivity
