### ISSUE TITLE
Downloads don't start, no error message

### ISSUE THREAD

**Issue by dcampbell503** [lanec/zoom-batch-downloader#16]
Hello,
After updating cloudlink.py with Account _ID, CLIENT_ID, CLIENT_SECRET, USERID, and PATH I run cloudlink.py and it sits at 
"Downloaded 0 files. Total size: 0B. Skipped: 0 files." with no error message.  Is it expected to see downloads start immediately or does it take time? 

![image](https://github.com/lanec/zoom-batch-downloader/assets/145501395/03bc2be6-541c-48f8-af17-b59fdc0f9002)

Thank you,

**Comment by AnessZurba** [comment]
Did you update the start_date and end_date as well?

**Comment by dcampbell503** [comment]
Yes date range was updated.

![image](https://github.com/lanec/zoom-batch-downloader/assets/145501395/40b7d510-189a-4937-8013-72a86c79556d)

**Comment by AnessZurba** [comment]
please enable `VERBOSE_OUTPUT` and see what gets printed
+ You are sure that you configured your credentials correctly and the user id actually has videos?

**Comment by AnessZurba** [comment]
I just pushed a tiny change to improve logging, not sure if it will help in this specific case, but might be worth it to use the latest version

**Comment by dcampbell503** [comment]
@AnessZurba I downloaded the latest version and use it successfully. 

Can Zoom-Batch-Downloader be modified to downloads all recordings on the Zoom account?

**Comment by AnessZurba** [comment]
it already downloads all the recordings, you just need to specify a wide enough range
like give it 1-1-2010 to 1-1-2030
that should download everything

**Comment by AnessZurba** [comment]
oh, you mean all the users. I'm not sure

**Comment by AnessZurba** [comment]
it should be possible, but I'll have to look into it

**Comment by dcampbell503** [comment]
@AnessZurba I appreciate you looking into it. 

The [Zoom Recording Downloader](https://github.com/ricardorodrigues-ca/zoom-recording-downloader) downloads all recordings but encountering unexpected issues.

Thanks

**Comment by AnessZurba** [comment]
@dcampbell503 please see the latest version

**Comment by dcampbell503** [comment]
@AnessZurba Downloaded latest version and encounter a 'first_name' error message. Confirmed the old version still works.

![image](https://github.com/lanec/zoom-batch-downloader/assets/145501395/f8e90051-3a66-4213-bcab-b8f985b6841e)

**Comment by AnessZurba** [comment]
@dcampbell503 pushed a new version

**Comment by dcampbell503** [comment]
@AnessZurba The script is working! I have almost 3 TB of Zoom recordings to download so will let it run and see if any errors stop it. 

One note others might find helpful, I had to temporarily disable Windows file length limit on the Windows VM where I'm running the script, long meeting name were generating errors.

 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled

**Comment by AnessZurba** [comment]
Glad to hear, I think this limit has been disabled on my machine since eternity so I didn't notice
PS: You might want to change CHUNK_SIZE if your internet speed is well beyond 1 MB/s,

**Comment by AnessZurba** [comment]
@dcampbell503 can I close this issue?
