### ISSUE TITLE
Problems with Path?

### ISSUE THREAD

**Issue by mingomongo** [lanec/zoom-batch-downloader#17]
Hi, I'm having issues with this code. It doesn't seem to like the path I'm inputting.
In this screenshot I try two paths. The first error is for "G:\Shared drives\xxx xxx\Zoom Recordings\Downloads New Script", where it doesn't recognise it at all (this is a Google Drive virtual drive). The second error is for "C:\Users\xxxxxxxxs Studio 10\Documents\Test" which gets an error.

I have all the requirements and they're fully updated.

![Batch downloader download path bug](https://github.com/lanec/zoom-batch-downloader/assets/33768220/75c24b0a-107e-4476-8d9d-3fc408fae30a)

**Comment by mingomongo** [comment]
This all works great, thanks a lot! A lot less hassle and better features than the one I used previously. Only thing I would add is a bit to the comment about users, they need to be separated by commas. Also I'm not sure if this script skips already downloaded videos?

**Comment by AnessZurba** [comment]
Glad to hear that, I'll edit the template file
The script should skip already downloaded files, is it not working for you?
