### ISSUE TITLE
[Suggestion] Choose what files to download from Zoom

### ISSUE THREAD

**Issue by abdo2048** [lanec/zoom-batch-downloader#19]
It would be awesome if i have the ability to download only video files, or audio files only for example. Instead of downloading the all recordings files in Zoom account, while I may just need the video files to be downloaded.
Thanks.

**Comment by AnessZurba** [comment]
Hi,
Added. Please see the new added `RECORDING_FILE_TYPES` parameter in `config_template.py`

**Comment by abdo2048** [comment]
Thank you so much
