### ISSUE TITLE
Downloads only last record when setting month or year in "END_DAY, END_MONTH, END_YEA" to greater value than the dates of my recordings in my account

### ISSUE THREAD

**Issue by abdo2048** [lanec/zoom-batch-downloader#20]
I set  `END_DAY, END_MONTH, END_YEAR` to `None , 9, 2023` and tried to download recordings form a Zoom account that has recordings in this month (September) and it worked fine and the script downloaded all the recordings in the account.

However, I have another Zoom account (completely different and separate from the first one), but it has recordings until August. I tried to run the script and set the date `END_DAY, END_MONTH, END_YEAR =` to `None , 9, 2023` as I did in the first time, but the script downloaded only the last record in Zoom account (I mean video because I set `RECORDING_FILE_TYPES` to download only MP4).

Things I have tried and failed:
1. Remove the MP4  value I set in `RECORDING_FILE_TYPES`.
2. I have made the range wide and changed the `START_DAY, START_MONTH, START_YEAR` to `None, 5, 2010` and the `END_DAY, END_MONTH, END_YEAR` to `None , 9, 2030`.
3. Deactivating the server-to-server app and activating in Zoom.
4. Regenerate `CLIENT_SECRET` of the app.
5. Deleting server-to-server app and creating new one.

What worked for me, is to set `END_DAY, END_MONTH, END_YEAR` to `None , 8, 2023`.
This means if I set it to `None , 9, 2023`, and September doesn't have recording, it will download only the lastrecord and ignore the rest. So I set `END_DAY, END_MONTH, END_YEAR` to the month where I have the last recording in Zoom, which is August.

I don't know, but the expected behavior that the script should work even if I set `END_DAY, END_MONTH, END_YEAR` to a value higher than than what I have in my Zoom account?
I mean that I set the `START_DAY, START_MONTH, START_YEAR` to `None, 5, 2020` and I don't have recordings in that year, but the script is working, but the script (or Zoom, I don't know) looks like is sensitive to `END_DAY, END_MONTH, END_YEAR` value!

**Comment by AnessZurba** [comment]
You actually uncovered a nasty bug. I see what's happening, will try to fix it

**Comment by AnessZurba** [comment]
for now try to work in batches where each batch range is no longer than a month

**Comment by AnessZurba** [comment]
and now it's fixed
شكرا
btw
Is anybody finding the "Press enter to exit" at the end of the script useful? I think it's pretty useless

**Comment by abdo2048** [comment]
Great thank you so much 🤩, I appreciate your efforts.
عفوا، أنت الذي تستحق الشكر 😄


For "Press enter to exit" option, I agree with you.

I'm actually thinking of creating a GUI for the script using any GUI framework like Tkinter for basic Windows users, and I searched a little bit from moments on how to do it.
Who knows, maybe I could do it, but at the same time, my work takes a lot of my time 😅 and I don't think I would be able to create the GUI before a month or so.
(FYI, I used in the past to write super basic codes, and now-times I'm able to read code and I can understand some of it + I'm a tech geek who likes to search and do different things in different fields, so I think I would be able to create the GUI with some research and the help of the AI 🤣.... but I don't have time these days 😔)

**Comment by AnessZurba** [comment]
I see. The problem with GUI is that it makes the development process way slower. and it takes too much effort.

The script as is today requires some tech know-how (creating the server-to-server app and what not) so I think it's fair to expect its users to be able to handle a terminal.

My feeling is that a GUI will hinder the experience not improve it, but that's just my biased opinion since I'm too lazy to build it.

**Comment by abdo2048** [comment]
I agree with you, but I didn't mean the GUI will be the main tool that people will use it.
I meant that people will use the script normally with the terminal and as they are doing now, and there will be GUI option for those who want it, but the GUI won't be updated each time the script has been updated.
What in my mind is that the GUI option could be behind the script development with some versions, and no problems with that, as long as the GUI is a stable build.
And from my point of view, you won't be doing the GUI, I think you should focus on the main development as you are now (You are doing great job 🎉😊👍 ), and another person could participate in the GUI thing.

**Comment by AnessZurba** [comment]
Can we close this issue?

**Comment by abdo2048** [comment]
YES, Thank you for your efforts
