### ISSUE TITLE
[Suggestion] Ability to download trash recordings

### ISSUE THREAD

**Issue by abdo2048** [lanec/zoom-batch-downloader#21]
It would be good if the script has the ability to download the recordings in the trash, or Zoom won't let you do this?

P.S. You should indicate in the README and in the script itself as a comment that the slash in the OUTPUT_PATH must be forward slash as in Linux and not backslash as in Windows. I know you set a placeholder value in the script that shows the path has forward slash, but some people in Windows will just copy and paste their path without noticing it.

**Comment by AnessZurba** [comment]
I can add trash

Not sure what do you mean by the thing about the slashes
You can copy Windows paths as is and it will work

**Comment by AnessZurba** [comment]
but downloading stuff from the trash is a very odd thing to do. Like why would you want to do that?

**Comment by AnessZurba** [comment]
Added option for trash, but you'll have to tell me if it's actually working.

**Comment by abdo2048** [comment]
**For the slash part:**
For Example, if I set the OUTPUT_PATH to something like `d:\Zoom8\07sa`, I receive an error:
`Error: [WinError 123] The filename, directory name, or volume label syntax is incorrect: d:\\Zoom8\07sa`

**For Trash part:**
Recordings are just in the trash because there are no enough space in Zoom 🤣, but I need the recordings in trash as well because I'm downloading all the recordings and upload them to Google Drive, we have good space in Google Drive and we will share the recordings afterwards from Google Drive instead of Zoom.
But it's not big deal, after I download the recordings in Zoom, I will delete them and restore the old recordings from trash that hasn't been downloaded and start to download them.

**Comment by AnessZurba** [comment]
Regarding the slash:
It's working for me, just make sure you are not doing double slashes (no need to escape it in last few versions).

Regarding the trash:
Fair enough, please try the latest version and see if it works.

**Comment by AnessZurba** [comment]
ok, the trash thing doesn't work
Will have to do it in a more structured way

**Comment by abdo2048** [comment]
If if takes too much efforts, then there is no need to do it as I illustrated before.
I appreciate your efforts and I value your time, I think you could put this time into something/feature more valuable.
Thank you again.

**Comment by AnessZurba** [comment]
OK
I looked into it again, you can't download stuff from the trash without recovering them first.

Theoretically, the script can be asked to recover stuff temporarily, download them and then delete them again. But I feel it's too much work.

**Comment by AnessZurba** [comment]
reverted the change I did earlier adding the trash option as it doesn't work

**Comment by abdo2048** [comment]
Okay, thank you so much, you did great job.
