### ISSUE TITLE
Script hangs, no output

### ISSUE THREAD

**Issue by jonwell** [lanec/zoom-batch-downloader#26]
Tested on Windows and Ubuntu with the same result. Followed the documentation to install and configure. When run there is no output, the command just hangs indefinitely until killed.  Verbose_output = true is no help because there's simply no output.

**Comment by AnessZurba** [comment]
Hi,
Are you able to debug it? if so, do you know on which line does it hang?

**Comment by AnessZurba** [comment]
Please try the new version, and let me know what does it output

**Comment by AnessZurba** [comment]
I've just pushed a change

**Comment by AnessZurba** [comment]
And another question, how did you open your PR if the script hangs? Does it hang before or after your changes?

**Comment by jonwell** [comment]
Hi! Ok I updated and ran with the debugger on... I had to leave it overnight, but I came back in to this error at line 80: 

Exception has occurred: SSLError
HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users?status=active&page_token=[my token] (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users?status=active&page_token=[my token (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

There's more but it's pretty long.

Just to check, I specified one user, and it worked fine. I had been limiting the dates for testing, but not the user... I have a pretty big account, over 10,000 users total. Not sure if that makes a difference.

**Comment by AnessZurba** [comment]
wait, so you are saying that when running with one user it works, but when trying to download from all users it just hangs?

**Comment by AnessZurba** [comment]
another thing, in the last time you ran, it didn't hang?

**Comment by jonwell** [comment]
Hi! Correct, when I specified one user it worked fine. When I did not specify, it appeared to hang, even when I specified a date range in which there is only one recording.

I am not a programmer so my language may be inaccurate. I interpreted this as hanging, since there was no response, no output, no error, etc. However, after leaving it all night, it generated the error above. I'm not sure if it would have done this before your update or not. 

-jw

**Comment by AnessZurba** [comment]
Hi,
I pushed a new version, it should improve stuff. let me know how it goes

**Comment by AnessZurba** [comment]
[zoom_batch_downloader.zip](https://github.com/lanec/zoom-batch-downloader/files/14295777/zoom_batch_downloader.zip)
Please also try this version after it, and see if it's any better

**Comment by jonwell** [comment]
Hi! OK I ran the version from yesterday and it hung on line 90 after 16 hours, with the same SSL error as before. 

Running the current version now and it's counting up... at 21:00 currently. About how long do you think is reasonable to let it go before we can assume it's going to fail?

Also, maybe related maybe not- would it be possible to use wildcards to specify a domain instead of a specific user? I only need recordings from my staff, not my students. If I could filter by staff domain (*@domain.com or similar) it may make things easier.

**Comment by AnessZurba** [comment]
We can filter the users by domain. But I'm really interested in understanding what makes it fail
As long as the progress bar is moving, it's not stuck
So you took the latest version and ran it, for how long is it running now? What does it show?

**Comment by AnessZurba** [comment]
I'm also not sure if filtering the users will help you, since it seems to be failing while scanning the for users, so adding a filter might not help

**Comment by AnessZurba** [comment]
Notice that the latest version available from github is different from the one I sent in the thread here

**Comment by jonwell** [comment]
Roger that, we'll keep at it.

Currently running, 28 minutes and counting. It just shows 'Scanning for users' and the timer.

Just saw your last message- Ok, I'll kill this one and try the newest. Thanks!

**Comment by jonwell** [comment]
Sure thing. Assuming it goes on like before it will just sit here and count up until however much time passes-

![Screenshot 2024-02-15 093255](https://github.com/lanec/zoom-batch-downloader/assets/10748670/e7011818-f389-4476-948b-5418e2c7909e)

**Comment by AnessZurba** [comment]
wait, so the progress bar isn't moving?
That's interesting
Are you sure you gave the app all the needed permissions?


> Required Scopes for your server-to-server zoom app:
> 
> - recording:read:admin to download the recordings.
> - user:read:admin if you want the script to iterate over all users in the account (default behavior).

**Comment by jonwell** [comment]
Correct, it looks just like that. At first the 'time remaining' (I assume) timer will count down, but when it hits zero the primary timer keeps counting up. No progress bar moves.

And yes, those permissions are granted- 
![image](https://github.com/lanec/zoom-batch-downloader/assets/10748670/768679fc-6718-48c0-99d8-bf4ec6c8b9ee)

**Comment by AnessZurba** [comment]
Are you running through a managed network? Can you try using another network? maybe from your mobile phone?

**Comment by AnessZurba** [comment]
and another thing to try

open a terminal in the script folder and run the following 

```
python -m venv .venv
.\.venv\scripts\activate
python -m pip install -r .\requirements.txt
python .\zoom_batch_downloader.py
```

**Comment by jonwell** [comment]
Hi! OK, running the commands above, it initiated a new environment, and is currently running... the progress bar actually went across this time, but now it's sitting at 12 minutes and counting, just like before. I'll let it go while I try on another network. It is a managed network, but I'm the one who manages it and I can't think of anything that would be causing a problem here. But I'll try and let you know!

**Comment by jonwell** [comment]
Hello! OK so the test on my off-network device crashed with the same error, but in much less time (sorry it's very blurry, I'm remoting in to it) 

![image](https://github.com/lanec/zoom-batch-downloader/assets/10748670/660934dd-ac5f-411b-befe-8b6f95786a6a)

The one running on my usual environment (using the commands above) is closing in on 4 hours, usual presentation.

**Comment by AnessZurba** [comment]
Regarding the first one, it's closing in on 4 hours with a progress bar that's still moving? or is it stuck?

**Comment by AnessZurba** [comment]
and the last one, did the progress bar actually move? or did just jump from 0 to 100 then crash?

**Comment by AnessZurba** [comment]
Actually the error message on your remote machine looks promising, I would try running it again

when running for the second time there is no need for all of the commands

These are enough
```
.\.venv\scripts\activate
python .\zoom_batch_downloader.py
```

**Comment by jonwell** [comment]
Roger that running again on the off-network system.  The progress bar is moving normally as the timer counts up/down, it's guessing it'll run about 3-4 minutes.  OK done, and once it hits 100% the progress bar disappears, it remains at 'scanning for users:' and the timer keeps ticking up (currently: [05:40<00:00])

The on-network one the progress bar never moves, there's no % increment or anything. It just sits as shown in the screenshot from 6 hours ago (vscode window).

**Comment by AnessZurba** [comment]
You did say that in your on-network instance the progress bar did move when running in venv (using the commands I gave you)

I'm now confident in saying that your problems are mostly network-related. The script might still be at fault for failing to handle these cases 

please run these commands on your on-network device

```
.\.venv\scripts\activate
python -m pip install ndg-httpsclient
python -m pip install pyopenssl
python -m pip install pyasn1
python .\zoom_batch_downloader.py
```

and I'd ask you to try on a third device, with a different network configuration, but not sure if that's even possible for you. If you could try a mobile network (4G/5G) from a mobile hotspot that would nice

**Comment by jonwell** [comment]
Hi again! Sorry for the slow replies, it's a holiday weekend so I'll be getting back to this less often. Also want to say I appreciate you working on this with me. For some context, we (the school district I work for) needs to shrink our Zoom cloud storage to save money, but we need to retain at least the audio from some meetings. So, this will be a big help when we get it going.

Anyway! OK on a 3rd device, a Macbook, connected to my 4g hotspot. Same result. Progress bar went up to 100%, disappeared, the counter is still counting. Been about an hour now and I have to pack it up, so I can't wait to see if it does the SSL error again (sorry). Seems like it is going longer this time than it did on the system that generated that error the other day. More like the original one. Anyway, back to this later!

**Comment by AnessZurba** [comment]
Ok, I have a theory

Please update to the latest version

and then replace `zoom_client.py` with this file

[zoom_client.zip](https://github.com/lanec/zoom-batch-downloader/files/14324135/zoom_client.zip)

**Comment by jonwell** [comment]
Hi Aness, I updated to the new version, including the file above, and I get this error: 

Scanning for users:
|                                                                                                                                                                                                                                                                                             | [00:00<?]
Traceback (most recent call last):
  File "C:\Users\jwells\OneDrive - sccs.net\Documents\PowerShell\Scripts\zoom-batch-downloader-master\zoom_batch_downloader.py", line 244, in <module>
    main()
  File "C:\Users\jwells\OneDrive - sccs.net\Documents\PowerShell\Scripts\zoom-batch-downloader-master\zoom_batch_downloader.py", line 35, in main
    file_count, total_size, skipped_count = download_recordings(get_users(), from_date, to_date)
                                                                ^^^^^^^^^^^
  File "C:\Users\jwells\OneDrive - sccs.net\Documents\PowerShell\Scripts\zoom-batch-downloader-master\zoom_batch_downloader.py", line 70, in get_users
    users = client.paginate_reduce(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwells\OneDrive - sccs.net\Documents\PowerShell\Scripts\zoom-batch-downloader-master\zoom_client.py", line 49, in paginate_reduce
    page = self.get(initial_url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'

**Comment by jonwell** [comment]
OK, interesting result here. The progress bar goes up and it looks like it makes a new line for each page of users. It indicated it was getting page x/17, but then when it reached 17 it continued counting and errored on each page. Now it looks like: 

![image](https://github.com/lanec/zoom-batch-downloader/assets/10748670/d81b4908-98e5-4987-9fbb-fc23d8f2f1b6)

**Comment by AnessZurba** [comment]
OK, we found a bug in Zoom APIs

please try this file now
[zoom_client.zip](https://github.com/lanec/zoom-batch-downloader/files/14324939/zoom_client.zip)

**Comment by AnessZurba** [comment]
This last file will probably work, but I still want to see what errors does it print

**Comment by jonwell** [comment]
Very exciting!

OK it's running now. At first it output a bunch of errors, with the same 'reached page x of 17' (and more which I'll paste below). But now it's cycling through accounts looking for recordings, I'll keep an eye on that. (Update: ok it is downloading files, neat!)

What I found interesting is the error text. I redacted a bunch of stuff, but note the name of the user. On each error, the user in the first bit is Milo, then later it lists another user. The second user changes as it's cycling through accounts I imagine, but each time the first name/account in the error output is Milo.

15%|████████████████████████▎                                                                                                                                     | [00:14<01:11]Error: reached page 26 of 17
{'page_count': 169, 'page_number': 1, 'page_size': 30, 'total_records': 5065, 'next_page_token': 'xxx', 'users': [{'id': 'xxx', **'first_name': 'Milo',** 'last_name': 'xxx', 'display_name': 'xxx', 'email': **'mxxx@net'**, 'type': 1, 'pmi': xxx, 'timezone': 'America/Los_Angeles', 'verified': 0, 'created_at': '2020-08-16T17:38:43Z', 'last_login_time': '2022-04-27T17:29:09Z', 'last_client_version': '5.0.4301.0407(chromeos)', 'pic_url': 'xxx', 'language': 'en-US', 'phone_number': '', 'status': 'active', 'role_id': '2', 'user_created_at': '2020-08-16T17:38:43Z'}, {'id': 'xxx', 'first_name': 'Palmer', 'last_name': 'xxx', 'display_name': 'Palmer xxx', 'email': 'pxxx@net',

**Comment by AnessZurba** [comment]
ok, very interesting 
I'm trying to figure out what is happening exactly, so please bear with me
can you try this file
[zoom_client.zip](https://github.com/lanec/zoom-batch-downloader/files/14350879/zoom_client.zip)

if it does print errors, what are the errors? and how many are there?

**Comment by AnessZurba** [comment]
sent you a DM on reddit

**Comment by AnessZurba** [comment]
OK.....

It seems like it's a bug of mine...
Please try this file. It should print no errors

[zoom_client.zip](https://github.com/lanec/zoom-batch-downloader/files/14379672/zoom_client.zip)

**Comment by jonwell** [comment]
Running now, it's going through users with no errors at the start. Cool! I'll let it go and let you know how it ends up. Thanks!

**Comment by AnessZurba** [comment]
Thanks for bringing this to my attention. In the end it seems it all stemmed from a silly bug on my end

I pushed a new version of the script that should address this issue correctly. It's slightly better than what I sent you here.

**Comment by jonwell** [comment]
I'll run the new version and let you know how it goes. I started the other one (linked above) before you posted that and it was working so I let it go overnight. Came back in to some SSL errors, which I can post if you want. Or I can run the new version and see if the same thing happens. Let me know!

**Comment by AnessZurba** [comment]
Please use the latest version, if there are any errors during the downloading stage, you can just run it again and it will skip any files that were already downloaded

**Comment by jonwell** [comment]
Hi Aness,

Seems to be working! I made it through a year of downloads with no errors. Awesome, thank you for your help. 

I would still suggest a way to narrow down the accounts between listing individual accounts and doing all of them, just because the bulk of the time spent when sifting through 5000 accounts is scanning each individual one for recordings. The actual download itself is relatively quick. But if you're not in a huge hurry you can just let it run and it'll finish...eventually. Anyway, thanks again!

**Comment by AnessZurba** [comment]
It will be added at some point, and thanks for helping me uncover a serious bug in my code :)
