### ISSUE TITLE
Can't add scope

### ISSUE THREAD

**Issue by Ambermai23** [lanec/zoom-batch-downloader#28]
Hello, I've used this on a different Zoom account without issues. However, I just tried to use it on another account, I am an admin, and I can't add these scopes. 
user:read:list_recordings:admin
user:read:list_recordings

Looks like Zoom changed something: https://devforum.zoom.us/t/recording-scope-not-found/106441/6 . 

Any ideas what I can do? Thank you.

**Comment by AnessZurba** [comment]
> Required Scopes for your server-to-server zoom app:
>
> `recording:read:admin` to download the recordings.
> `user:read:admin` if you want the script to iterate over all users in the account (default behavior).

**Comment by jld224** [comment]
The scopes are also not available for me, this seems really strange. I'm on my 4th zoom downloader and i've run into this scope issue 3 times now, zoom must not want people to be doing it this way

![image](https://github.com/lanec/zoom-batch-downloader/assets/122399022/562e2ac7-5c50-420a-bb37-1e1f7271669f)
![image](https://github.com/lanec/zoom-batch-downloader/assets/122399022/33235f10-7667-45e9-8ec5-02d362a34086)

**Comment by AnessZurba** [comment]
It appears to be an issue on Zoom's side when migrating to the new granular scopes
They replied to the link you posted, and I found another [thread ](https://devforum.zoom.us/t/granular-scopes-missing-team-chatbatch-members/106546/4) saying they will be deploying a fix over the weekend

Once it's pushed, please reply here with the scopes you ended up adding, I think I will update the README to address this

**Comment by Ambermai23** [comment]
How exciting to have found a bug and have it not just me being stupid! I am going out of office next week but when I come back I'll take another look. Thank you for your time on this.

**Comment by AndriiLabaG** [comment]
Hey, just an update, the scopes are fixed now, you need to add: user:read:list_users:admin, cloud_recording:read:list_user_recordings:admin, cloud_recording:read:list_recording_files:admin

**Comment by AnessZurba** [comment]
README updated. Thanks for the heads up

**Comment by AnessZurba** [comment]
@Ambermai23 if it's working for you know, please let me know so that I can close this issue.
