### ISSUE TITLE
KeyError on meetings

### ISSUE THREAD

**Issue by sanaking** [lanec/zoom-batch-downloader#3]
I just installed this and all the requirements and i'm getting this error:

> https://api.zoom.us/v2/users/xxxxxxxxxxxxxxxxxx/recordings?from=2018-01-01&to=2018-02-01&page_size=300&
Traceback (most recent call last):
  File "cloudlink.py", line 89, in <module>
    main()
  File "cloudlink.py", line 38, in main
    get_recording(start_date, next_date)
  File "cloudlink.py", line 64, in get_recording
    for meeting in data['meetings']:
KeyError: 'meetings'

**Comment by assaf416** [comment]
plus 1

**Comment by AnessZurba** [comment]
please try the latest version if you are still having a problem. Note that you need to use server to server auth instead of JWT as JWT is deprecated now

**Comment by AnessZurba** [comment]
closed due to inactivity
